# Generated by Django 3.2.20 on 2023-10-13 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=20)),
                ('pin', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=80)),
                ('Password', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=20)),
                ('pin', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=30)),
                ('pin', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('department', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='StudentComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('reply', models.CharField(max_length=200)),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.staff')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('date', models.DateField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=40)),
                ('COLLEGE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.college')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=300)),
                ('reply', models.CharField(max_length=300)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='CollegeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('COLLEGE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.college')),
            ],
        ),
        migrations.AddField(
            model_name='college',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.login'),
        ),
    ]
