# Generated by Django 3.2.20 on 2023-10-13 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_app', '0002_staff_department_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='COLLEGE',
        ),
        migrations.AddField(
            model_name='staff',
            name='COLLEGE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='smart_app.college'),
            preserve_default=False,
        ),
    ]
