# Generated by Django 3.2.20 on 2023-10-16 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_app', '0006_department_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='COLLEGE',
        ),
    ]
