# Generated by Django 3.2.20 on 2023-10-16 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_app', '0009_remove_department_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='COLLEGE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='smart_app.college'),
            preserve_default=False,
        ),
    ]
