# Generated by Django 3.2.20 on 2023-10-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_app', '0010_department_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
