# Generated by Django 3.2.20 on 2023-10-17 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_app', '0011_rating_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='COLLEGE',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
    ]
