# Generated by Django 3.2.20 on 2023-10-17 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_app', '0013_student_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Camera',
        ),
    ]
