# Generated by Django 3.2.20 on 2023-10-17 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_app', '0014_delete_camera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('COLLEGE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.college')),
                ('DEPARTMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.department')),
            ],
        ),
    ]
