# Generated by Django 3.2.20 on 2023-11-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_app', '0015_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
