# Generated by Django 3.2.20 on 2023-11-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_app', '0017_emotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotions',
            name='Emotion',
            field=models.CharField(max_length=30),
        ),
    ]
